(library
 (name well_cap)
 (public_name well.cap)
 (libraries well well_html))

(rule
 (targets cap_css.ml)
 (deps cap.css)
 (action (with-stdout-to %{targets}
  (progn (echo "let css = {cap_css|") (cat %{deps}) (echo "|cap_css}")))))

(rule
 (targets cap_js.ml)
 (deps web/register.bc.js)
 (action (with-stdout-to %{targets}
  (progn (echo "let js = {cap_js|") (cat %{deps}) (echo "|cap_js}")))))
