(* Well adapter generation on top of a Cyrograf schema.

   The Cyrograf library owns the message types and the [to_drut]/[from_drut]
   conversions. This module only emits the Well integration layer: an [IMPL]
   module type, [make_spec] returning a text-Drut [Well.Service.drut_spec], and
   convenience callers. It never declares message types and never re-implements
   a codec; every conversion goes through the generated public functions. *)

module Schema = Cyrograf.Schema
module Compiler = Cyrograf_compiler
module Info = Cyrograf_compiler.Info

type artifact = { path : string; contents : string }

let ocaml_keywords =
  [ "and"; "as"; "assert"; "asr"; "begin"; "class"; "constraint"; "do";
    "done"; "downto"; "else"; "end"; "exception"; "external"; "false";
    "for"; "fun"; "function"; "functor"; "if"; "in"; "include"; "inherit";
    "initializer"; "land"; "lazy"; "let"; "lor"; "lsl"; "lsr"; "lxor";
    "match"; "method"; "mod"; "module"; "mutable"; "new"; "nonrec";
    "object"; "of"; "open"; "or"; "private"; "rec"; "sig"; "struct";
    "then"; "to"; "true"; "try"; "type"; "val"; "virtual"; "when";
    "while"; "with" ]

let escape_keyword name =
  if List.mem name ocaml_keywords then name ^ "'" else name

let snake_case name =
  let buf = Buffer.create (String.length name + 8) in
  String.iteri
    (fun i c ->
      if c >= 'A' && c <= 'Z' then begin
        if i > 0 then Buffer.add_char buf '_';
        Buffer.add_char buf (Char.lowercase_ascii c)
      end
      else Buffer.add_char buf c)
    name;
  Buffer.contents buf

let rec display_type = function
  | Schema.Primitive p -> Schema.primitive_name p
  | Schema.Reference q -> Schema.qualified_name q
  | Schema.List inner -> "List<" ^ display_type inner ^ ">"
  | Schema.Optional inner -> display_type inner ^ "?"

let field_info (field : Schema.field) =
  Printf.sprintf
    "{ Well.Service.pname = %S; ptype = %S; poptional = %b }"
    field.name (display_type field.type_)
    (match field.type_ with Schema.Optional _ -> true | _ -> false)

let params_of schema (q : Schema.qualified) =
  match Schema.find_message schema q with
  | Some { kind = Schema.Struct fields; _ } -> List.map field_info fields
  | _ -> []

let params_list schema q =
  String.concat "; " (params_of schema q)

(* The generated data library exposes messages through its wrapper module. *)
let data_module = "Contract_data"

let qualified_type ~library (q : Schema.qualified) =
  library ^ "." ^ Info.qualified_message Compiler.Ocaml
    ~module_name:q.module_name ~message_name:q.message_name ^ ".t"

let qualified_fn ~library ~fn (q : Schema.qualified) =
  library ^ "." ^ Info.qualified_message Compiler.Ocaml
    ~module_name:q.module_name ~message_name:q.message_name ^ "." ^ fn

let method_ident name = escape_keyword (Info.normalize_method Compiler.Ocaml name)

let adapter_module_name (m : Schema.module_) =
  Info.module_symbol Compiler.Ocaml ~module_name:m.name

let generate_module ~library ~schema (m : Schema.module_) =
  let buf = Buffer.create 1024 in
  let p fmt = Printf.bprintf buf fmt in
  let local = m.name in
  p "(* Generated by Well. Do not edit. *)\n\n";
  p "module type IMPL = sig\n";
  List.iter
    (fun (method_ : Schema.method_) ->
      p "  val %s : Well.rpc_ctx -> %s -> %s\n"
        (method_ident method_.name)
        (qualified_type ~library method_.request)
        (qualified_type ~library method_.response))
    m.methods;
  p "end\n\n";
  p
    "let _service_ref :\n  (string -> Yojson.Safe.t -> string -> \
     (string, Well.Service.drut_error) result) option ref = ref None\n\n";
  p "let make_spec (module I : IMPL) : Well.Service.drut_spec =\n";
  p "  { Well.Service.dname = %S\n" local;
  p "  ; drpcs = [\n";
  List.iter
    (fun (method_ : Schema.method_) ->
      p "      { Well.Service.rname = %S\n" method_.name;
      p "      ; params = [%s]\n" (params_list schema method_.request);
      p "      ; returns = [%s]\n" (params_list schema method_.response);
      p "      ; returns_name = %S };\n"
        method_.response.message_name)
    m.methods;
  p "    ]\n";
  p "  ; dhandler = (fun rpc_name ctx_wire payload_text ->\n";
  p "      let ctx = Well.rpc_ctx_of_wire ctx_wire in\n";
  p "      match rpc_name with\n";
  List.iter
    (fun (method_ : Schema.method_) ->
      let ident = method_ident method_.name in
      p "      | %S ->\n" method_.name;
      p "        (match %s payload_text with\n"
        (qualified_fn ~library ~fn:"from_drut" method_.request);
      p "         | Error e ->\n";
      p
        "           Error (Well.Service.Drut_request_error \
         (Cyrograf.Error.to_string e))\n";
      p "         | Ok request ->\n";
      p "           (try\n";
      p "              (match %s (I.%s ctx request) with\n"
        (qualified_fn ~library ~fn:"to_drut" method_.response)
        ident;
      p "               | Ok text -> Ok text\n";
      p "               | Error e ->\n";
      p
        "                 Error (Well.Service.Drut_response_error \
         (Cyrograf.Error.to_string e)))\n";
      p
        "            with exn ->\n              Error (Well.Service.Drut_handler_error \
         (Printexc.to_string exn))))\n")
    m.methods;
  p
    "      | _ -> Error (Well.Service.Drut_dispatch_error (\"Unknown RPC: \" ^ \
     rpc_name)))\n";
  p "  ; dset_ref = (fun f -> _service_ref := Some f)\n";
  p "  }\n\n";
  List.iter
    (fun (method_ : Schema.method_) ->
      let ident = method_ident method_.name in
      p "let %s ~ctx request =\n" ident;
      p "  let ctx_wire = Well.rpc_ctx_to_wire ctx in\n";
      p "  match %s request with\n"
        (qualified_fn ~library ~fn:"to_drut" method_.request);
      p "  | Error e ->\n";
      p "    Error (Well.Service.Drut_request_error (Cyrograf.Error.to_string e))\n";
      p "  | Ok payload_text ->\n";
      p "    (match !_service_ref with\n";
      p "     | None ->\n";
      p
        "       Error (Well.Service.Drut_dispatch_error (%S ^ \": service not \
         registered\"))\n"
        local;
      p "     | Some f -> f %S ctx_wire payload_text)\n\n" method_.name)
    m.methods;
  Buffer.contents buf

let generate ~library ~schema =
  let adapters =
    List.filter_map
      (fun (m : Schema.module_) ->
        if m.methods = [] then None
        else
          Some
            { path = "adapters/" ^ snake_case m.name ^ ".ml";
              contents = generate_module ~library ~schema m })
      schema.modules
  in
  if adapters = [] then []
  else
    let dune =
      { path = "adapters/dune";
        contents =
          "(library\n (name contract)\n (wrapped false)\n (libraries \
           contract_data well.core cyrograf yojson))\n" }
    in
    dune :: adapters

(* ── Browser (js_of_ocaml) adapter ────────────────────────────────────
   Client-only proxy for the browser. It links neither [well.core] nor Eio,
   SQLite or the Cyrograf compiler; the transport is plain XHR that sends the
   text [to_drut] payload and reads the text response. The generated callback
   shape [Proxy.<method> request ~on_done] is preserved. *)

let browser_library = "Contract_data_browser"

let browser_rpc_source =
  {|(* Generated by Well. Do not edit. *)
open Js_of_ocaml

let csrf_token () : string =
  let doc = Dom_html.document in
  match
    Js.Opt.to_option (doc##querySelector (Js.string "meta[name='csrf-token']"))
  with
  | Some el -> (try Js.to_string (Js.Unsafe.get el (Js.string "content")) with _ -> "")
  | None ->
    (try
       Js.to_string
         (Js.Unsafe.get Js.Unsafe.global (Js.string "__WELL_CSRF"))
     with _ -> "")

let error_message (text : string) : string option =
  match Yojson.Safe.from_string text with
  | `Assoc fields ->
    (match List.assoc_opt "error" fields with
     | Some (`String s) -> Some s
     | _ -> None)
  | _ -> None
  | exception _ -> None

let post ~(service : string) ~(method_ : string) ~(payload : string)
    ~(on_done : (string, string) result -> unit) : unit =
  let url = Printf.sprintf "/rpc/%s/%s" service method_ in
  let xhr = XmlHttpRequest.create () in
  xhr##_open (Js.string "POST") (Js.string url) Js._true;
  xhr##setRequestHeader (Js.string "Content-Type") (Js.string "application/json");
  xhr##setRequestHeader (Js.string "X-Requested-With")
    (Js.string "XMLHttpRequest");
  Js.Unsafe.set xhr (Js.string "withCredentials") Js._true;
  let token = csrf_token () in
  if token <> "" then
    xhr##setRequestHeader (Js.string "X-CSRF-Token") (Js.string token);
  xhr##.onreadystatechange :=
    Js.wrap_callback (fun _ ->
      if xhr##.readyState = XmlHttpRequest.DONE then
        let text = Js.Opt.case xhr##.responseText (fun () -> "") Js.to_string in
        let status = xhr##.status in
        if status >= 200 && status < 300 then
          (match error_message text with
           | Some msg -> on_done (Error msg)
           | None -> on_done (Ok text))
        else
          match error_message text with
          | Some s -> on_done (Error s)
          | None ->
            if status = 0 then on_done (Error "Network error")
            else
              on_done
                (Error
                   (Printf.sprintf "RPC %s.%s: %d" service method_ status)));
  xhr##send (Js.Opt.return (Js.string payload))
|}

let browser_ref (q : Schema.qualified) =
  browser_library ^ "."
  ^ Info.qualified_message Compiler.Ocaml ~module_name:q.module_name
      ~message_name:q.message_name

let generate_browser_module (m : Schema.module_) =
  let buf = Buffer.create 1024 in
  let p fmt = Printf.bprintf buf fmt in
  p "(* Generated by Well. Do not edit. *)\n\n";
  p "module Proxy = struct\n";
  List.iter
    (fun (method_ : Schema.method_) ->
      let ident = method_ident method_.name in
      p "  let %s (req : %s.t)\n" ident (browser_ref method_.request);
      p "      ~(on_done : (%s.t, string) result -> unit) : unit =\n"
        (browser_ref method_.response);
      p "    match %s.to_drut req with\n" (browser_ref method_.request);
      p "    | Error e -> on_done (Error (Cyrograf.Error.to_string e))\n";
      p "    | Ok payload ->\n";
      p "      Rpc.post ~service:%S ~method_:%S ~payload\n" m.name method_.name;
      p "        ~on_done:(function\n";
      p "          | Error e -> on_done (Error e)\n";
      p "          | Ok text ->\n";
      p "            (match %s.from_drut text with\n" (browser_ref method_.response);
      p "             | Ok value -> on_done (Ok value)\n";
      p "             | Error e -> on_done (Error (Cyrograf.Error.to_string e))))\n\n")
    m.methods;
  p "end\n";
  Buffer.contents buf

let generate_browser ~(schema : Schema.t) =
  let modules =
    List.filter (fun (m : Schema.module_) -> m.methods <> []) schema.modules
  in
  if modules = [] then []
  else
    let dune =
      { path = "adapters_browser/dune";
        contents =
          "(library\n (name contract_browser)\n (wrapped false)\n (libraries \
           contract_data_browser cyrograf yojson js_of_ocaml)\n (preprocess \
           (pps js_of_ocaml-ppx)))\n" }
    in
    { path = "adapters_browser/rpc.ml"; contents = browser_rpc_source }
    :: dune
    :: List.map
         (fun (m : Schema.module_) ->
           { path = "adapters_browser/" ^ snake_case m.name ^ ".ml";
             contents = generate_browser_module m })
         modules

(* ── Network client proxies (TS, Go, Dart) ────────────────────────────
   Each target gets a [Proxy] that sends the target's own [toDrut] text and
   decodes the response through the target's own [fromDrut]. Only the two
   public conversions are used. *)

let ts_base name =
  let artifact = Info.data_artifact Compiler.Typescript ~module_name:name in
  Filename.basename artifact |> Filename.remove_extension

let dart_base name =
  let artifact = Info.data_artifact Compiler.Dart ~module_name:name in
  Filename.basename artifact |> Filename.remove_extension

let ts_ref (q : Schema.qualified) =
  Info.module_symbol Compiler.Typescript ~module_name:q.module_name
  ^ "." ^ Info.message_symbol Compiler.Typescript ~message_name:q.message_name

let referenced_modules (m : Schema.module_) =
  let seen = Hashtbl.create 8 in
  let add name = if name <> m.name then Hashtbl.replace seen name () in
  List.iter
    (fun (method_ : Schema.method_) ->
      add method_.request.module_name;
      add method_.response.module_name)
    m.methods;
  Hashtbl.fold (fun name () acc -> name :: acc) seen []
  |> List.sort String.compare

let ts_imports (m : Schema.module_) =
  let buf = Buffer.create 256 in
  List.iter
    (fun name ->
      Printf.bprintf buf "import * as %s from \"./%s.ts\";\n"
        (Info.module_symbol Compiler.Typescript ~module_name:name)
        (ts_base name))
    (List.sort String.compare
       (m.name :: referenced_modules m |> List.sort_uniq String.compare));
  Buffer.contents buf

let generate_ts_module (m : Schema.module_) =
  Printf.sprintf
    "export * from \"./%s.ts\";\n\
     export { createClient, RpcError, type ClientContext, type \
     TransportOptions } from \"./well_transport.ts\";\n"
    (ts_base m.name)

let go_ref (q : Schema.qualified) =
  if q.module_name = "" then Info.message_symbol Compiler.Go ~message_name:q.message_name
  else
    Info.module_symbol Compiler.Go ~module_name:q.module_name ^ "."
    ^ Info.message_symbol Compiler.Go ~message_name:q.message_name

let go_local_ref (q : Schema.qualified) =
  Info.message_symbol Compiler.Go ~message_name:q.message_name

let go_ref_for ~local (q : Schema.qualified) =
  if q.module_name = local then go_local_ref q
  else go_ref q

let generate_go_module ~go_module (m : Schema.module_) =
  let buf = Buffer.create 2048 in
  let p fmt = Printf.bprintf buf fmt in
  let package = Info.module_symbol Compiler.Go ~module_name:m.name in
  p "// Generated by Well. Do not edit.\n\n";
  p "package %s\n\n" package;
  p "import (\n\t\"bytes\"\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"io\"\n\t\"net/http\"\n";
  List.iter
    (fun name ->
      p "\n\t%S\n"
        (go_module ^ "/" ^ Info.module_symbol Compiler.Go ~module_name:name))
    (referenced_modules m);
  p ")\n\n";
  p "type Proxy struct {\n\tBaseURL    string\n\tHTTPClient *http.Client\n\tCSRFToken  string\n}\n\n";
  p "type ProxyResult[T any] struct {\n\tOk    bool\n\tValue T\n\tErr   error\n}\n\n";
  p "func wireError(text string) (string, bool) {\n";
  p "\tvar obj map[string]json.RawMessage\n";
  p "\tif err := json.Unmarshal([]byte(text), &obj); err != nil {\n\t\treturn \"\", false\n\t}\n";
  p "\traw, ok := obj[\"error\"]\n\tif !ok {\n\t\treturn \"\", false\n\t}\n";
  p "\tvar message string\n\tif err := json.Unmarshal(raw, &message); err != nil {\n\t\treturn \"\", false\n\t}\n";
  p "\treturn message, true\n}\n\n";
  p "func (p Proxy) post(service, method, payload string, onDone func(ProxyResult[string])) {\n";
  p "\tclient := p.HTTPClient\n\tif client == nil {\n\t\tclient = http.DefaultClient\n\t}\n";
  p "\turl := p.BaseURL + \"/rpc/\" + service + \"/\" + method\n";
  p "\trequest, err := http.NewRequest(\"POST\", url, bytes.NewBufferString(payload))\n";
  p "\tif err != nil {\n\t\tonDone(ProxyResult[string]{Err: err})\n\t\treturn\n\t}\n";
  p "\trequest.Header.Set(\"Content-Type\", \"application/json\")\n";
  p "\trequest.Header.Set(\"X-Requested-With\", \"XMLHttpRequest\")\n";
  p "\tif p.CSRFToken != \"\" {\n\t\trequest.Header.Set(\"X-CSRF-Token\", p.CSRFToken)\n\t}\n";
  p "\tresponse, err := client.Do(request)\n";
  p "\tif err != nil {\n\t\tonDone(ProxyResult[string]{Err: fmt.Errorf(\"network error: %%w\", err)})\n\t\treturn\n\t}\n";
  p "\tdefer response.Body.Close()\n";
  p "\tbody, _ := io.ReadAll(response.Body)\n\ttext := string(body)\n";
  p "\tif message, ok := wireError(text); ok {\n\t\tonDone(ProxyResult[string]{Err: fmt.Errorf(\"%%s\", message)})\n\t\treturn\n\t}\n";
  p "\tif response.StatusCode >= 200 && response.StatusCode < 300 {\n\t\tonDone(ProxyResult[string]{Ok: true, Value: text})\n\t\treturn\n\t}\n";
  p "\tonDone(ProxyResult[string]{Err: fmt.Errorf(\"rpc %%s.%%s: %%d\", service, method, response.StatusCode)})\n}\n\n";
  List.iter
    (fun (method_ : Schema.method_) ->
      let ident = Info.normalize_method Compiler.Go method_.name in
      let req = go_ref_for ~local:m.name method_.request in
      let resp = go_ref_for ~local:m.name method_.response in
      let req_from (q : Schema.qualified) =
        match q with
        | q when q.module_name = m.name ->
          Info.message_symbol Compiler.Go ~message_name:q.message_name ^ "FromDrut"
        | q ->
          Info.module_symbol Compiler.Go ~module_name:q.module_name ^ "."
          ^ Info.message_symbol Compiler.Go ~message_name:q.message_name
          ^ "FromDrut"
      in
      let req_to (q : Schema.qualified) =
        match q with
        | q when q.module_name = m.name ->
          Info.message_symbol Compiler.Go ~message_name:q.message_name ^ "ToDrut"
        | q ->
          Info.module_symbol Compiler.Go ~module_name:q.module_name ^ "."
          ^ Info.message_symbol Compiler.Go ~message_name:q.message_name
          ^ "ToDrut"
      in
      p "func (p Proxy) %s(request %s, onDone func(ProxyResult[%s])) {\n"
        ident req resp;
      p "\tpayload, err := %s(request)\n" (req_to method_.request);
      p "\tif err != nil {\n\t\tonDone(ProxyResult[%s]{Err: err})\n\t\treturn\n\t}\n" resp;
      p "\tp.post(%S, %S, payload, func(r ProxyResult[string]) {\n"
        m.name method_.name;
      p "\t\tif r.Err != nil {\n\t\t\tonDone(ProxyResult[%s]{Err: r.Err})\n\t\t\treturn\n\t\t}\n" resp;
      p "\t\tvalue, err := %s(r.Value)\n" (req_from method_.response);
      p "\t\tif err != nil {\n\t\t\tonDone(ProxyResult[%s]{Err: err})\n\t\t\treturn\n\t\t}\n" resp;
      p "\t\tonDone(ProxyResult[%s]{Ok: true, Value: value})\n\t})\n}\n\n" resp)
    m.methods;
  Buffer.contents buf

let dart_ref ~local (q : Schema.qualified) =
  let message = Info.message_symbol Compiler.Dart ~message_name:q.message_name in
  if q.module_name = local then message
  else Info.module_symbol Compiler.Dart ~module_name:q.module_name ^ "." ^ message

let generate_dart_module (m : Schema.module_) =
  let buf = Buffer.create 2048 in
  let p fmt = Printf.bprintf buf fmt in
  p "// Generated by Well. Do not edit.\n\n";
  p "import 'dart:convert';\nimport 'dart:io';\n\n";
  p "import '%s.dart';\n" (dart_base m.name);
  List.iter
    (fun name -> p "import '%s.dart' as %s;\n" (dart_base name)
        (Info.module_symbol Compiler.Dart ~module_name:name))
    (referenced_modules m);
  p "\nclass ProxyResult<T> {\n";
  p "  const ProxyResult.ok(this.value) : ok = true, error = null;\n";
  p "  const ProxyResult.error(this.error) : ok = false, value = null;\n";
  p "  final bool ok;\n  final T? value;\n  final String? error;\n}\n\n";
  p "class Proxy {\n";
  p "  Proxy({required this.baseUrl, this.csrfToken = ''});\n";
  p "  final String baseUrl;\n  final String csrfToken;\n\n";
  p "  Future<ProxyResult<String>> _post(String service, String method, String payload) async {\n";
  p "    final uri = Uri.parse('$baseUrl/rpc/$service/$method');\n";
  p "    final client = HttpClient();\n    try {\n";
  p "      final request = await client.postUrl(uri);\n";
  p "      request.headers.contentType = ContentType.json;\n";
  p "      request.headers.set('X-Requested-With', 'XMLHttpRequest');\n";
  p "      if (csrfToken.isNotEmpty) request.headers.set('X-CSRF-Token', csrfToken);\n";
  p "      request.write(payload);\n";
  p "      final response = await request.close();\n";
  p "      final text = await response.transform(utf8.decoder).join();\n";
  p "      final message = _wireError(text);\n";
  p "      if (message != null) return ProxyResult<String>.error(message);\n";
  p "      if (response.statusCode >= 200 && response.statusCode < 300) {\n";
  p "        return ProxyResult<String>.ok(text);\n      }\n";
  p "      return ProxyResult<String>.error('rpc $service.$method: ${response.statusCode}');\n";
  p "    } catch (e) {\n      return ProxyResult<String>.error('network error: $e');\n";
  p "    } finally {\n      client.close(force: true);\n    }\n  }\n\n";
  List.iter
    (fun (method_ : Schema.method_) ->
      let ident = Info.normalize_method Compiler.Dart method_.name in
      let req = dart_ref ~local:m.name method_.request in
      let resp = dart_ref ~local:m.name method_.response in
      p "  void %s(%s request, void Function(ProxyResult<%s>) onDone) {\n"
        ident req resp;
      p "    String payload;\n    try {\n      payload = request.toDrut();\n";
      p "    } catch (e) {\n      onDone(ProxyResult<%s>.error('RPC encode: $e'));\n      return;\n    }\n" resp;
      p "    _post(%S, %S, payload).then((r) {\n" m.name method_.name;
      p "      if (!r.ok) {\n        onDone(ProxyResult<%s>.error(r.error!));\n        return;\n      }\n" resp;
      p "      try {\n        onDone(ProxyResult<%s>.ok(%s.fromDrut(r.value!)));\n"
        resp resp;
      p "      } catch (e) {\n        onDone(ProxyResult<%s>.error('RPC decode: $e'));\n      }\n" resp;
      p "    });\n  }\n\n")
    m.methods;
  p "}\n\n";
  p "String? _wireError(String text) {\n";
  p "  try {\n    final decoded = jsonDecode(text);\n";
  p "    if (decoded is Map && decoded['error'] is String) {\n";
  p "      return decoded['error'] as String;\n    }\n";
  p "  } catch (_) { return null; }\n  return null;\n}\n";
  Buffer.contents buf

let ts_transport =
  {|import type { RpcContext } from "./rpc.ts";

export type TransportOptions = {
  baseUrl?: string;
  bearerToken?: string | (() => string | Promise<string>);
  fetch?: typeof globalThis.fetch;
  timeoutMs?: number;
};
export type ClientContext = RpcContext;
export class RpcError extends Error {
  constructor(message: string, readonly kind: "transport" | "http" | "protocol", readonly status?: number) {
    super(message);
    this.name = "RpcError";
  }
}
type GlobalWell = {
  __WELL_CSRF?: string;
  __WELL_BASE?: string;
  document?: { querySelector(selector: string): { getAttribute(name: string): string | null } | null };
};
function csrfToken(): string {
  const globals = globalThis as unknown as GlobalWell;
  return globals.document?.querySelector("meta[name='csrf-token']")?.getAttribute("content") || globals.__WELL_CSRF || "";
}
export function createClient(options: TransportOptions = {}): ClientContext {
  if (options.timeoutMs !== undefined && (!Number.isFinite(options.timeoutMs) || options.timeoutMs <= 0)) {
    throw new Error("timeoutMs must be a positive finite number");
  }
  const config = { ...options };
  return {
    async invoke(service, method, payload) {
      const controller = new AbortController();
      const timer = config.timeoutMs === undefined ? undefined : setTimeout(() => controller.abort(), config.timeoutMs);
      try {
        const bearer = config.bearerToken !== undefined;
        const headers: Record<string, string> = { "Content-Type": "application/json" };
        if (bearer) {
          const supplied = typeof config.bearerToken === "function" ? config.bearerToken() : config.bearerToken;
          const token = await Promise.race([
            Promise.resolve(supplied),
            new Promise<never>((_resolve, reject) => controller.signal.addEventListener("abort", () => reject(new Error("aborted")), { once: true })),
          ]);
          if (!token || /[\s\x00-\x1f\x7f]/.test(token)) throw new RpcError("Invalid bearer token", "transport");
          headers.Authorization = `Bearer ${token}`;
        } else {
          headers["X-Requested-With"] = "XMLHttpRequest";
          const csrf = csrfToken();
          if (csrf) headers["X-CSRF-Token"] = csrf;
        }
        const base = (config.baseUrl ?? (globalThis as unknown as GlobalWell).__WELL_BASE ?? "").replace(/\/$/, "");
        const response = await (config.fetch ?? globalThis.fetch)(`${base}/rpc/${service}/${method}`, {
          method: "POST", headers, body: payload,
          credentials: bearer ? "omit" : "include",
          redirect: bearer ? "error" : "follow",
          signal: controller.signal,
        });
        const text = await response.text();
        if (!response.ok) throw new RpcError(`RPC ${service}.${method}: ${response.status}`, "http", response.status);
        let hasError = false;
        try { const parsed = JSON.parse(text); hasError = !!parsed && typeof parsed === "object" && typeof parsed.error === "string"; } catch {}
        if (hasError) throw new RpcError(`RPC ${service}.${method}: protocol error`, "protocol", response.status);
        return text;
      } catch (error) {
        if (error instanceof RpcError) throw error;
        throw new RpcError(controller.signal.aborted ? "RPC transport timed out" : "RPC transport failed", "transport");
      } finally {
        if (timer !== undefined) clearTimeout(timer);
      }
    },
  };
}
|}

let generate_clients ~go_module ~targets ~(schema : Schema.t) =
  let modules =
    List.filter (fun (m : Schema.module_) -> m.methods <> []) schema.modules
  in
  if modules = [] then []
  else
    let out = ref [] in
    if List.mem Compiler.Typescript targets then
      out := { path = "typescript/well_transport.ts"; contents = ts_transport } :: !out;
    if List.mem Compiler.Typescript targets then
      List.iter
        (fun (m : Schema.module_) ->
          out :=
            { path = "typescript/proxy_" ^ ts_base m.name ^ ".ts";
              contents = generate_ts_module m }
            :: !out)
        modules;
    if List.mem Compiler.Go targets then
      List.iter
        (fun (m : Schema.module_) ->
          out :=
            { path =
                "go/" ^ Info.module_symbol Compiler.Go ~module_name:m.name
                ^ "/proxy.go";
              contents = generate_go_module ~go_module m }
            :: !out)
        modules;
    if List.mem Compiler.Dart targets then
      List.iter
        (fun (m : Schema.module_) ->
          out :=
            { path = "dart/proxy_" ^ dart_base m.name ^ ".dart";
              contents = generate_dart_module m }
            :: !out)
        modules;
    List.rev !out
